/**
 * Vendor Ed25519 public key for offline licence verification (hex, 32 bytes).
 *
 * Generated by `node scripts/licence-keygen.mjs genkeys`; its private pair
 * lives in .keys/licence-ed25519.private.hex (gitignored) and is the ONLY key
 * that may sign licence keys (`issue` subcommand). Rotating: generate a new
 * pair, embed the new public key, and keep signing with its private key —
 * old licences verify only against the key that signed them, so ship
 * overlapping keys in `verify.ts` before cutting over.
 */
export const LICENCE_PUBLIC_KEY_HEX =
  'b3190c8d90d3f4e292cd40d54eef7c346841549d3f8609f0771d390499ca859e';
